name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: ventus-ag/vks-action@master
        with: 
          authUrl: ${{ secrets.AUTHURL }}
          projectName: ${{ secrets.PROJECTNAME }}
          projectDomainName: ${{ secrets.PROJECTDOMAINNAME }}
          userName: ${{ secrets.USERNAME }}
          userDomainName: ${{ secrets.USERDOMAINNAME }}
          userPassword: ${{ secrets.USERPASSWORD }}
          clusterName: ${{ secrets.CLUSTERNAME }}
